# Imports

In [2]:
%matplotlib inline

In [3]:
#importing necessary libraries
import matplotlib.pyplot as plt
import numpy as np
from mplsoccer import Pitch, Sbopen, VerticalPitch
import pandas as pd
from scipy.stats.contingency import odds_ratio
from warnings import filterwarnings
filterwarnings('ignore')

# UPPOR per player per match EURO2004

In [5]:
def uppor_player(player="Bruno Miguel Borges Fernandes"):
    odds = []
    for match in [3930166,3930174,3938644,3941020,3942349]:
        parser = Sbopen()
        df= parser.event(match)[0]
        passes = df.loc[df['team_name'] == "Portugal"].loc[df['type_name'] == 'Pass'].loc[df['sub_type_name'] != 'Throw-in'].loc[df['sub_type_name'] != 'Corner'].loc[df['sub_type_name'] != 'Free Kick'].loc[df['sub_type_name'] != 'Kick Off'].loc[df['sub_type_name'] != 'Goal Kick'].set_index('id')  
        df_pass = passes.loc[passes.player_name==player, ['x', 'y', 'end_x', 'end_y','under_pressure','pass_length']]
        df_pass_long=df_pass.loc[df_pass.pass_length>10.9361]
        df_pass_not_long=df_pass.loc[df_pass.pass_length<=10.9361]
        df_pass_pressure=df_pass.loc[df_pass.under_pressure==1]
        df_pass_not_pressure=df_pass.loc[df_pass.under_pressure!=1]
        df_pass_long_pressure=df_pass_long.loc[df_pass_long.under_pressure==1]
        df_pass_long_not_pressure=df_pass_long.loc[df_pass_long.under_pressure!=1]
        df_pass_not_long_pressure=df_pass_not_long.loc[df_pass_not_long.under_pressure==1]
        df_pass_not_long_not_pressure=df_pass_not_long.loc[df_pass_not_long.under_pressure!=1]
        res = odds_ratio([[len(df_pass_long_pressure),len(df_pass_long_not_pressure)],[len(df_pass_not_long_pressure),len(df_pass_not_long_not_pressure)]],kind='sample')
        number = [[len(df_pass_long_pressure),len(df_pass_long_not_pressure)],[len(df_pass_not_long_pressure),len(df_pass_not_long_not_pressure)]]
        odds.append((player,number,res.statistic,res.confidence_interval(confidence_level=0.95)))
    df_odds=pd.DataFrame(odds,columns=["Nome","Passes","UPPOR","Intervalo de confiança"])
    return df_odds

In [6]:
uppor_player()

,Nome,Passes,UPPOR,Intervalo de confiança
0,Bruno Miguel Borges Fernandes,"[[9, 57], [3, 20]]",1.052632,"(0.25894832563212866, 4.278974340893564)"
1,Bruno Miguel Borges Fernandes,"[[8, 20], [3, 8]]",1.066667,"(0.22419372179604022, 5.074976090601095)"
2,Bruno Miguel Borges Fernandes,"[[0, 0], [0, 0]]",NaN,"(0, inf)"
3,Bruno Miguel Borges Fernandes,"[[10, 64], [2, 17]]",1.328125,"(0.26557748645059515, 6.641813051247242)"
4,Bruno Miguel Borges Fernandes,"[[2, 28], [3, 15]]",0.357143,"(0.05363581924944425, 2.3780940086877655)"

# UPPOR in certain match - all players

In [8]:
def uppor_match(team_name="Portugal",match="3942349"):
    parser = Sbopen()
    df= parser.event(match)[0]
    passes = df.loc[df['team_name'] == team_name].loc[df['type_name'] == 'Pass'].loc[df['sub_type_name'] != 'Throw-in'].loc[df['sub_type_name'] != 'Corner'].loc[df['sub_type_name'] != 'Free Kick'].loc[df['sub_type_name'] != 'Kick Off'].loc[df['sub_type_name'] != 'Goal Kick'].set_index('id')
    odds = []
    for name in passes.player_name.unique():
        df_pass = passes.loc[passes.player_name==name, ['x', 'y', 'end_x', 'end_y','under_pressure','pass_length']]
        df_pass_long=df_pass.loc[df_pass.pass_length>10.9361]
        df_pass_not_long=df_pass.loc[df_pass.pass_length<=10.9361]
        df_pass_pressure=df_pass.loc[df_pass.under_pressure==1]
        df_pass_not_pressure=df_pass.loc[df_pass.under_pressure!=1]
        df_pass_long_pressure=df_pass_long.loc[df_pass_long.under_pressure==1]
        df_pass_long_not_pressure=df_pass_long.loc[df_pass_long.under_pressure!=1]
        df_pass_not_long_pressure=df_pass_not_long.loc[df_pass_not_long.under_pressure==1]
        df_pass_not_long_not_pressure=df_pass_not_long.loc[df_pass_not_long.under_pressure!=1]
        res = odds_ratio([[len(df_pass_long_pressure),len(df_pass_long_not_pressure)],[len(df_pass_not_long_pressure),len(df_pass_not_long_not_pressure)]],kind='sample')
        number = [[len(df_pass_long_pressure),len(df_pass_long_not_pressure)],[len(df_pass_not_long_pressure),len(df_pass_not_long_not_pressure)]]
        odds.append((name,number,res.statistic,res.confidence_interval(confidence_level=0.95)))
    df_odds=pd.DataFrame(odds,columns=["Nome","Passes","UPPOR","Intervalo de confiança"])
    return df_odds

In [9]:
uppor_match()

,Nome,Passes,UPPOR,Intervalo de confiança
0,João Maria Lobo Alves Palhinha Gonçalves,"[[8, 45], [2, 12]]",1.066667,"(0.1997492333386356, 5.696030761974935)"
1,Bruno Miguel Borges Fernandes,"[[2, 28], [3, 15]]",0.357143,"(0.05363581924944425, 2.3780940086877655)"
2,Kléper Laveran Lima Ferreira,"[[5, 103], [0, 29]]",inf,"(nan, inf)"
3,Diogo Meireles Costa,"[[5, 21], [0, 0]]",NaN,"(0, inf)"
4,Rúben Santos Gato Alves Dias,"[[3, 86], [0, 17]]",inf,"(nan, inf)"
5,João Pedro Cavaco Cancelo,"[[0, 33], [1, 12]]",0.000000,"(0.0, nan)"
6,Nuno Mendes,"[[0, 71], [1, 19]]",0.000000,"(0.0, nan)"
7,Rafael Alexandre Conceição Leão,"[[3, 27], [0, 6]]",inf,"(nan, inf)"
8,Cristiano Ronaldo dos Santos Aveiro,"[[4, 7], [3, 10]]",1.904762,"(0.3207309561097801, 11.312029115737626)"
9,Bernardo Mota Veiga de Carvalho e Silva,"[[5, 47], [0, 27]]",inf,"(nan, inf)"
10,Vitor Machado Ferreira,"[[8, 68], [3, 24]]",0.941176,"(0.23067126228209628, 3.8401539057155474)"
11,Nélson Cabral Semedo,"[[0, 15], [1, 8]]",0.000000,"(0.0, nan)"
12,Francisco Fernandes Conceição,"[[1, 23], [0, 9]]",inf,"(nan, inf)"
13,Rúben Diogo Da Silva Neves,"[[4, 28], [0, 10]]",inf,"(nan, inf)"
14,João Félix Sequeira,"[[0, 5], [0, 2]]",NaN,"(0, inf)"

# UPPOR per player all matches - cumulative

In [11]:
def uppor_player_cumulative(player="Bruno Miguel Borges Fernandes"):
    odds = []
    passes_long_pressure=0
    passes_long_not_pressure=0
    passes_not_long_pressure=0
    passes_not_long_not_pressure=0
    for match in [3930166,3930174,3938644,3941020,3942349]:
        parser = Sbopen()
        df= parser.event(match)[0]
        passes = df.loc[df['team_name'] == "Portugal"].loc[df['type_name'] == 'Pass'].loc[df['sub_type_name'] != 'Throw-in'].loc[df['sub_type_name'] != 'Corner'].loc[df['sub_type_name'] != 'Free Kick'].loc[df['sub_type_name'] != 'Kick Off'].loc[df['sub_type_name'] != 'Goal Kick'].set_index('id')  
        df_pass = passes.loc[passes.player_name==player, ['x', 'y', 'end_x', 'end_y','under_pressure','pass_length']]
        df_pass_long=df_pass.loc[df_pass.pass_length>10.9361]
        df_pass_not_long=df_pass.loc[df_pass.pass_length<=10.9361]
        df_pass_pressure=df_pass.loc[df_pass.under_pressure==1]
        df_pass_not_pressure=df_pass.loc[df_pass.under_pressure!=1]
        df_pass_long_pressure=df_pass_long.loc[df_pass_long.under_pressure==1]
        df_pass_long_not_pressure=df_pass_long.loc[df_pass_long.under_pressure!=1]
        df_pass_not_long_pressure=df_pass_not_long.loc[df_pass_not_long.under_pressure==1]
        df_pass_not_long_not_pressure=df_pass_not_long.loc[df_pass_not_long.under_pressure!=1]
        passes_long_pressure += len(df_pass_long_pressure)
        passes_long_not_pressure += len(df_pass_long_not_pressure)
        passes_not_long_pressure += len(df_pass_not_long_pressure)
        passes_not_long_not_pressure += len(df_pass_not_long_not_pressure)
        res = odds_ratio([[passes_long_pressure,passes_long_not_pressure],[passes_not_long_pressure,passes_not_long_not_pressure]],kind='sample')
        number = [[passes_long_pressure,passes_long_not_pressure],[passes_not_long_pressure,passes_not_long_not_pressure]]
    odds.append((player,number,res.statistic,res.confidence_interval(confidence_level=0.95)))
    df_odds=pd.DataFrame(odds,columns=["Nome","Passes","UPPOR","Intervalo de confiança"])
    return df_odds

In [12]:
uppor_player_cumulative()

,Nome,Passes,UPPOR,Intervalo de confiança
0,Bruno Miguel Borges Fernandes,"[[29, 169], [11, 60]]",0.935987,"(0.440385485985204, 1.9893294856768704)"

In [13]:
def list_players(team_name="Portugal"):
    list_team_players = []
    for match in [3930166,3930174,3938644,3941020,3942349]:
        parser = Sbopen()
        df= parser.event(match)[0]
        passes = df.loc[df['team_name'] == team_name].loc[df['type_name'] == 'Pass'].loc[df['sub_type_name'] != 'Throw-in'].loc[df['sub_type_name'] != 'Corner'].loc[df['sub_type_name'] != 'Free Kick'].loc[df['sub_type_name'] != 'Kick Off'].loc[df['sub_type_name'] != 'Goal Kick'].set_index('id')
        for name in passes.player_name.unique():
            if name not in list_team_players: 
                list_team_players.append(name)
    return list_team_players

In [14]:
def uppor_all_players_cumulative(team_name="Portugal"):
    df_uppor=pd.DataFrame()
    for name in list_players():
        df_uppor=pd.concat([df_uppor,uppor_player_cumulative(name)])
    return df_uppor

In [15]:
uppor_all_players_cumulative()

,Nome,Passes,UPPOR,Intervalo de confiança
0,Nuno Mendes,"[[20, 224], [14, 68]]",0.433673,"(0.20796587659965127, 0.9043439295229432)"
0,João Pedro Cavaco Cancelo,"[[19, 152], [9, 50]]",0.694444,"(0.29532039778891406, 1.632982652164964)"
0,Bruno Miguel Borges Fernandes,"[[29, 169], [11, 60]]",0.935987,"(0.440385485985204, 1.9893294856768704)"
0,Rúben Santos Gato Alves Dias,"[[22, 298], [5, 70]]",1.033557,"(0.37820621175918573, 2.8244913387142314)"
0,Kléper Laveran Lima Ferreira,"[[25, 305], [1, 60]]",4.918033,"(0.6538052184282558, 36.99426956399001)"
0,Bernardo Mota Veiga de Carvalho e Silva,"[[17, 138], [12, 80]]",0.821256,"(0.3732320194421124, 1.807083652744681)"
0,José Diogo Dalot Teixeira,"[[7, 57], [1, 28]]",3.438596,"(0.403131885145712, 29.330217393278698)"
0,Diogo Meireles Costa,"[[20, 96], [0, 2]]",inf,"(nan, inf)"
0,Rafael Alexandre Conceição Leão,"[[11, 70], [6, 25]]",0.654762,"(0.21914605616426458, 1.9562896062619015)"
0,Vitor Machado Ferreira,"[[32, 198], [15, 64]]",0.689562,"(0.3511101665653283, 1.3542648332796572)"
0,Cristiano Ronaldo dos Santos Aveiro,"[[16, 30], [12, 33]]",1.466667,"(0.5980736860355044, 3.596732578840479)"
0,Gonçalo Bernardo Inácio,"[[6, 97], [5, 40]]",0.494845,"(0.14282174529661934, 1.714528348755346)"
0,Diogo José Teixeira da Silva,"[[8, 17], [1, 10]]",4.705882,"(0.5107156705852499, 43.36136522763429)"
0,Francisco Fernandes Conceição,"[[9, 76], [2, 38]]",2.250000,"(0.46303439734852003, 10.933313008686746)"
0,Pedro Lomba Neto,"[[4, 44], [2, 35]]",1.590909,"(0.2752262417682929, 9.196040752785406)"
0,João Maria Lobo Alves Palhinha Gonçalves,"[[15, 115], [11, 42]]",0.498024,"(0.21190483130236865, 1.1704670421688876)"
0,Rúben Diogo Da Silva Neves,"[[10, 77], [2, 20]]",1.298701,"(0.26328541846572195, 6.406070921348906)"
0,Nélson Cabral Semedo,"[[0, 28], [3, 19]]",0.000000,"(0.0, nan)"
0,António João Pereira Albuquerque Tavares Silva,"[[3, 48], [2, 12]]",0.375000,"(0.05621586756976507, 2.501517917970072)"
0,João Neves,"[[3, 41], [2, 26]]",0.951220,"(0.14875559991944085, 6.082584863163024)"
0,João Félix Sequeira,"[[6, 38], [1, 25]]",3.947368,"(0.4478531725523482, 34.79202204312227)"
0,Danilo Luís Hélio Pereira,"[[0, 76], [2, 8]]",0.000000,"(0.0, nan)"
0,Matheus Luiz Nunes,"[[2, 10], [2, 3]]",0.300000,"(0.02871088598790419, 3.134699501712233)"
0,Gonçalo Matias Ramos,"[[0, 1], [0, 0]]",NaN,"(0, inf)"

# UPPOR all player all matches - cumulative

In [17]:
def list_players(team_name="Portugal"):
    list_team_players = []
    for match in [3930166,3930174,3938644,3941020,3942349]:
        parser = Sbopen()
        df= parser.event(match)[0]
        passes = df.loc[df['team_name'] == team_name].loc[df['type_name'] == 'Pass'].loc[df['sub_type_name'] != 'Throw-in'].loc[df['sub_type_name'] != 'Corner'].loc[df['sub_type_name'] != 'Free Kick'].loc[df['sub_type_name'] != 'Kick Off'].loc[df['sub_type_name'] != 'Goal Kick'].set_index('id')
        for name in passes.player_name.unique():
            if name not in list_team_players: 
                list_team_players.append(name)
    return list_team_players

In [18]:
def uppor_all_players_cumulative(team_name="Portugal"):
    df_uppor=pd.DataFrame()
    for name in list_players():
        df_uppor=pd.concat([df_uppor,uppor_player_cumulative(name)]).sort_values(by=["UPPOR"])
    return df_uppor

In [19]:
uppor_all_players_cumulative()

,Nome,Passes,UPPOR,Intervalo de confiança
0,Nélson Cabral Semedo,"[[0, 28], [3, 19]]",0.000000,"(0.0, nan)"
0,Danilo Luís Hélio Pereira,"[[0, 76], [2, 8]]",0.000000,"(0.0, nan)"
0,Matheus Luiz Nunes,"[[2, 10], [2, 3]]",0.300000,"(0.02871088598790419, 3.134699501712233)"
0,António João Pereira Albuquerque Tavares Silva,"[[3, 48], [2, 12]]",0.375000,"(0.05621586756976507, 2.501517917970072)"
0,Nuno Mendes,"[[20, 224], [14, 68]]",0.433673,"(0.20796587659965127, 0.9043439295229432)"
0,Gonçalo Bernardo Inácio,"[[6, 97], [5, 40]]",0.494845,"(0.14282174529661934, 1.714528348755346)"
0,João Maria Lobo Alves Palhinha Gonçalves,"[[15, 115], [11, 42]]",0.498024,"(0.21190483130236865, 1.1704670421688876)"
0,Rafael Alexandre Conceição Leão,"[[11, 70], [6, 25]]",0.654762,"(0.21914605616426458, 1.9562896062619015)"
0,Vitor Machado Ferreira,"[[32, 198], [15, 64]]",0.689562,"(0.3511101665653283, 1.3542648332796572)"
0,João Pedro Cavaco Cancelo,"[[19, 152], [9, 50]]",0.694444,"(0.29532039778891406, 1.632982652164964)"
0,Bernardo Mota Veiga de Carvalho e Silva,"[[17, 138], [12, 80]]",0.821256,"(0.3732320194421124, 1.807083652744681)"
0,Bruno Miguel Borges Fernandes,"[[29, 169], [11, 60]]",0.935987,"(0.440385485985204, 1.9893294856768704)"
0,João Neves,"[[3, 41], [2, 26]]",0.951220,"(0.14875559991944085, 6.082584863163024)"
0,Rúben Santos Gato Alves Dias,"[[22, 298], [5, 70]]",1.033557,"(0.37820621175918573, 2.8244913387142314)"
0,Rúben Diogo Da Silva Neves,"[[10, 77], [2, 20]]",1.298701,"(0.26328541846572195, 6.406070921348906)"
0,Cristiano Ronaldo dos Santos Aveiro,"[[16, 30], [12, 33]]",1.466667,"(0.5980736860355044, 3.596732578840479)"
0,Pedro Lomba Neto,"[[4, 44], [2, 35]]",1.590909,"(0.2752262417682929, 9.196040752785406)"
0,Francisco Fernandes Conceição,"[[9, 76], [2, 38]]",2.250000,"(0.46303439734852003, 10.933313008686746)"
0,José Diogo Dalot Teixeira,"[[7, 57], [1, 28]]",3.438596,"(0.403131885145712, 29.330217393278698)"
0,João Félix Sequeira,"[[6, 38], [1, 25]]",3.947368,"(0.4478531725523482, 34.79202204312227)"
0,Diogo José Teixeira da Silva,"[[8, 17], [1, 10]]",4.705882,"(0.5107156705852499, 43.36136522763429)"
0,Kléper Laveran Lima Ferreira,"[[25, 305], [1, 60]]",4.918033,"(0.6538052184282558, 36.99426956399001)"
0,Diogo Meireles Costa,"[[20, 96], [0, 2]]",inf,"(nan, inf)"
0,Gonçalo Matias Ramos,"[[0, 1], [0, 0]]",NaN,"(0, inf)"

# Team UPPOR per match

In [56]:
def uppor_team():
    odds = []
    for match in [3930166,3930174,3938644,3941020,3942349]:
        parser = Sbopen()
        df= parser.event(match)[0]
        passes = df.loc[df['team_name'] == "Portugal"].loc[df['type_name'] == 'Pass'].loc[df['sub_type_name'] != 'Throw-in'].loc[df['sub_type_name'] != 'Corner'].loc[df['sub_type_name'] != 'Free Kick'].loc[df['sub_type_name'] != 'Kick Off'].loc[df['sub_type_name'] != 'Goal Kick'].set_index('id')  
        df_pass = passes[['x', 'y', 'end_x', 'end_y','under_pressure','pass_length']]
        df_pass_long=df_pass.loc[df_pass.pass_length>10.9361]
        df_pass_not_long=df_pass.loc[df_pass.pass_length<=10.9361]
        df_pass_pressure=df_pass.loc[df_pass.under_pressure==1]
        df_pass_not_pressure=df_pass.loc[df_pass.under_pressure!=1]
        df_pass_long_pressure=df_pass_long.loc[df_pass_long.under_pressure==1]
        df_pass_long_not_pressure=df_pass_long.loc[df_pass_long.under_pressure!=1]
        df_pass_not_long_pressure=df_pass_not_long.loc[df_pass_not_long.under_pressure==1]
        df_pass_not_long_not_pressure=df_pass_not_long.loc[df_pass_not_long.under_pressure!=1]
        res = odds_ratio([[len(df_pass_long_pressure),len(df_pass_long_not_pressure)],[len(df_pass_not_long_pressure),len(df_pass_not_long_not_pressure)]],kind='sample')
        number = [[len(df_pass_long_pressure),len(df_pass_long_not_pressure)],[len(df_pass_not_long_pressure),len(df_pass_not_long_not_pressure)]]
        odds.append((match,number,res.statistic,res.confidence_interval(confidence_level=0.95)))
    df_odds=pd.DataFrame(odds,columns=["Jogo","Passes","UPPOR","Intervalo de confiança"])
    return df_odds

In [58]:
uppor_team()

,Jogo,Passes,UPPOR,Intervalo de confiança
0,3930166,"[[60, 487], [27, 133]]",0.606890,"(0.3706747291274969, 0.9936360806058636)"
1,3930174,"[[64, 357], [28, 119]]",0.761905,"(0.4666871094378811, 1.243871652920424)"
2,3938644,"[[36, 448], [19, 200]]",0.845865,"(0.47348754889176514, 1.5110999803688998)"
3,3941020,"[[76, 506], [33, 166]]",0.755540,"(0.48435237543300774, 1.178563571339416)"
4,3942349,"[[48, 607], [14, 200]]",1.129678,"(0.6098918602851245, 2.09245523339237)"

# Team UPPOR all matches

In [60]:
def uppor_team_all(team_name="Portugal"):
    odds = []
    passes_long_pressure=0
    passes_long_not_pressure=0
    passes_not_long_pressure=0
    passes_not_long_not_pressure=0
    for match in [3930166,3930174,3938644,3941020,3942349]:
        parser = Sbopen()
        df= parser.event(match)[0]
        passes = df.loc[df['team_name'] == team_name].loc[df['type_name'] == 'Pass'].loc[df['sub_type_name'] != 'Throw-in'].loc[df['sub_type_name'] != 'Corner'].loc[df['sub_type_name'] != 'Free Kick'].loc[df['sub_type_name'] != 'Kick Off'].loc[df['sub_type_name'] != 'Goal Kick'].set_index('id')  
        df_pass = passes[['x', 'y', 'end_x', 'end_y','under_pressure','pass_length']]
        df_pass_long=df_pass.loc[df_pass.pass_length>10.9361]
        df_pass_not_long=df_pass.loc[df_pass.pass_length<=10.9361]
        df_pass_pressure=df_pass.loc[df_pass.under_pressure==1]
        df_pass_not_pressure=df_pass.loc[df_pass.under_pressure!=1]
        df_pass_long_pressure=df_pass_long.loc[df_pass_long.under_pressure==1]
        df_pass_long_not_pressure=df_pass_long.loc[df_pass_long.under_pressure!=1]
        df_pass_not_long_pressure=df_pass_not_long.loc[df_pass_not_long.under_pressure==1]
        df_pass_not_long_not_pressure=df_pass_not_long.loc[df_pass_not_long.under_pressure!=1]
        passes_long_pressure += len(df_pass_long_pressure)
        passes_long_not_pressure += len(df_pass_long_not_pressure)
        passes_not_long_pressure += len(df_pass_not_long_pressure)
        passes_not_long_not_pressure += len(df_pass_not_long_not_pressure)
        res = odds_ratio([[passes_long_pressure,passes_long_not_pressure],[passes_not_long_pressure,passes_not_long_not_pressure]],kind='sample')
        number = [[passes_long_pressure,passes_long_not_pressure],[passes_not_long_pressure,passes_not_long_not_pressure]]
    odds.append((team_name,number,res.statistic,res.confidence_interval(confidence_level=0.95)))
    df_odds=pd.DataFrame(odds,columns=["Equipa","Passes","UPPOR","Intervalo de confiança"])
    return df_odds

In [62]:
uppor_team_all()

,Equipa,Passes,UPPOR,Intervalo de confiança
0,Portugal,"[[284, 2405], [121, 818]]",0.798309,"(0.6361356243235393, 1.0018268525041492)"